name = "TDEP"
uuid = "03dde086-6832-4aef-a599-2e26e563d57c"
authors = ["ejmeitz <emeitz@andrew.cmu.edu>"]
version = "0.0.1"

[deps]
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
AtomsCalculators = "a3e0e189-c65a-42c1-833c-339540406eb1"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
PeriodicTable = "7b2266bf-644c-5ea3-82d8-af4bbd25a884"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TDEP_jll = "1616d667-7f4b-50a1-9dcc-173d58025fb3"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[weakdeps]
Molly = "aa0f7f06-fcc0-5ec4-a7f3-a573f33f9c4c"

[extensions]
MolecularDynamicsExt = "Molly"

[compat]
AtomsBase = "0.5.1"
AtomsCalculators = "0.2.3"
DelimitedFiles = "1.9.1"
FastGaussQuadrature = "1.0.2"
LinearAlgebra = "1.11.0"
MPI = "0.20.22"
Molly = "0.22"
PeriodicTable = "1.2.1"
Printf = "1.11.0"
ProgressMeter = "1.10.4"
Reexport = "1.2.2"
StaticArrays = "1.9.13"
StatsBase = "0.34.5"
TDEP_jll = "25.3.0"
Unitful = "1.23.1"
julia = "1.6"
